version: '3.4'

networks:
    backend:
        driver: bridge
services:
  identity.api:
    image: ${DOCKER_REGISTRY-}identityapi
    ports:
        - 5001:8080
    build:
      context: .
      dockerfile: Identity.API/Dockerfile
    container_name: identity.api
    environment:
        - ASPNETCORE_ENVIRONMENT=Development
    networks:
        - backend

  bookcatalog.api:
    image: ${DOCKER_REGISTRY-}bookcatalogapi
    container_name: bookcatalog.api
    ports:
        - 5002:8080
    build:
      context: .
      dockerfile: BookCatalog.API/Dockerfile
    depends_on:
        - identity.api
        - rabbitmq 
    environment:
        - ASPNETCORE_ENVIRONMENT=Development
    networks:
        - backend

  basket.api:
    ports:
        - 5003:8080
    image: ${DOCKER_REGISTRY-}basketapi
    container_name: basket.api
    build:
      context: .
      dockerfile: Basket.API/Dockerfile
    depends_on:
        - identity.api
        - rabbitmq
    environment:
        - ASPNETCORE_ENVIRONMENT=Development
    networks:
        - backend

  apigateway:
    image: ${DOCKER_REGISTRY-}apigateway
    container_name: apigateway
    ports:
        - 6001:8080
    build:
      context: ..
      dockerfile: src/APIGateway/Dockerfile
    networks:
        - backend

  contentrecsys:
    image: ${DOCKER_REGISTRY-}contentrecsys
    container_name: contentrecsys
    ports:
        - 5004:8080
    build:
      context: ..\src\ContentRecSys
      dockerfile: Dockerfile
    networks:
        - backend

  rabbitmq:
    image: rabbitmq:3-management-alpine
    networks:
        - backend

  ordering.api:
    image: ${DOCKER_REGISTRY-}orderingapi
    container_name: ordering.api
    ports:
        - 5005:8080
    build:
      context: ..
      dockerfile: src/Ordering.API/Dockerfile
    networks:
        - backend
    depends_on:
        - rabbitmq
        - identity.api
