version: '3.4'

networks:
    backend:
        driver: bridge
services:
  identity.api:
    image: ${DOCKER_REGISTRY-}identityapi
    build:
      context: .
      dockerfile: Identity.API/Dockerfile
    container_name: identity.api
    environment:
        - ASPNETCORE_ENVIRONMENT=Development
    networks:
        - backend

  bookcatalog.api:
    image: ${DOCKER_REGISTRY-}bookcatalogapi
    container_name: bookcatalog.api
    build:
      context: .
      dockerfile: BookCatalog.API/Dockerfile
    depends_on:
        - identity.api
    environment:
        - ASPNETCORE_ENVIRONMENT=Development
    networks:
        - backend

  basket.api:
    image: ${DOCKER_REGISTRY-}basketapi
    container_name: basket.api
    build:
      context: .
      dockerfile: Basket.API/Dockerfile
    depends_on:
        - identity.api
    environment:
        - ASPNETCORE_ENVIRONMENT=Development
    networks:
        - backend

  apigateway:
    image: ${DOCKER_REGISTRY-}apigateway
    container_name: apigateway
    ports:
        - 6001:8080
    build:
      context: ..
      dockerfile: src/APIGateway/Dockerfile
    networks:
        - backend
